INSERT INTO categories (title) VALUES
    ('Dairy'),
    ('Meat'),
    ('Veggies'),
    ('Fruits');

    INSERT INTO items (name, description, img_url, category_id) VALUES
        ('Milk', 'Whole Milk, H.E.B., half gallon','https://i.imgur.com/tIFtvKk.jpg', 1),
        ('Milk', 'Whole Milk, H.E.B., one gallon','https://i.imgur.com/jO4jNEb.jpg', 1),
        ('Milk', 'Whole Milk, H.E.B., small','https://i.imgur.com/gWJD7wV.jpg', 1),
        ('Milk', 'Soy Milk, Organic, Central Market, half gallon','https://i.imgur.com/Wn1y7NQ.jpg', 1),
        ('Milk', 'Almond Milk, Organic, H.E.B, half gallon','https://i.imgur.com/4P9NK2G.jpg', 1),
        ('Apples', 'Fresh Medium Red Delicious, H.E.B', 'https://i.imgur.com/13FXViG.jpg', 4),
        ('Bananas', 'Fresh Bananas Bunch, H.E.B', 'https://i.imgur.com/1stL1sy.jpg', 4),
        ('Grapes', 'Fresh Red Seeded Globe Grapes, H.E.B', 'https://i.imgur.com/kHpb2gy.jpg', 4),
        ('Pineapple', 'Fresh Pineapple, H.E.B', 'https://i.imgur.com/TCjiOXw.jpg', 4),
        ('Strawberries', 'Organic Strawberries 1 lb, H.E.B', 'https://i.imgur.com/yccJlyX.jpg', 4),
        ('Oranges', 'Fresh Navel Oranges, H.E.B', 'https://i.imgur.com/kg8gxhu.jpg', 4),
        ('Lemons', 'Yellow Fresh Extra Large, H.E.B', 'https://i.imgur.com/dyAv075.jpg', 4),
        ('Limes', 'Green Fresh Extra Large, H.E.B', 'https://i.imgur.com/YOchQo6.jpg', 4),
        ('Grapefruit', 'Fresh Large, H.E.B', 'https://i.imgur.com/hJargQT.jpg', 4),
        ('Mandarins', 'Fresh Minneola Tangelos, H.E.B', 'https://i.imgur.com/WGDgHdQ.jpg', 4),
        ('Watermelon', 'Fresh Seedless Watermelon, H.E.B', 'https://i.imgur.com/VjHUpKS.jpg', 4),
        ('Mangos', 'Fresh Small Mangos, H.E.B', 'https://i.imgur.com/nZiigtM.jpg', 4),
        ('Avocados', 'Fresh Avocados, H.E.B', 'https://i.imgur.com/kqlklnk.jpg', 3),
        ('Tomatoes', 'Fresh Organic, H.E.B', 'https://i.imgur.com/pCNbkBS.jpg',3),
        ('Lettuce', 'Fresh Green Leaf, H.E.B', 'https://i.imgur.com/3NgmuzL.jpg',3),
        ('Cucumbers', 'Fresh Cucumbers, H.E.B', 'https://i.imgur.com/F6b6fF4.jpg',3),
        ('Onions', 'Red Onions, H.E.B', 'https://i.imgur.com/mS5P6sC.jpg', 3),
        ('Onions', 'Yellow Onions, H.E.B', 'https://i.imgur.com/zmIYCku.jpg', 3),
        ('Garlic', 'Garlic Pod, H.E.B', 'https://i.imgur.com/HHX5fLg.jpg', 3),
        ('Peppers', 'Red Bell Peppers, H.E.B', 'https://i.imgur.com/CoyTDNp.jpg', 3);